# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/fuyifeng/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git osx autojump zsh-completions zsh-autosuggestions)

#autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[[ -s /usr/local/Cellar/autojump/22.5.1/etc/profile.d/autojump.sh ]] && . /usr/local/Cellar/autojump/22.5.1/etc/profile.d/autojump.sh


alias ll='ls -l' 
alias la='ls -a' 
alias rm='rm -i' 
alias vi='vim' 
alias grep="grep --color=auto" 
alias g='git' 
alias dk='docker' 
alias osbt='sbt -Dsbt.override.build.repos=true'
alias ctagsjava='ctags -R --extra=+q --languages=java'
alias ctagsc='ctags -R --extra=+q --languages=c,c++'
alias ctagsjavac='ctags -R --extra=+q --languages=java,c,c++'
alias sp='/usr/local/bin/sshprodwrapper.sh'
alias st2='/usr/local/bin/sshtest2wrapper.sh'
alias st1='/usr/local/bin/sshtest1wrapper.sh'
alias ss='/usr/local/bin/sshstagwrapper.sh'
alias sd='/usr/local/bin/sshdevwrapper.sh'
alias suat='/usr/local/bin/sshuat.sh'

alias -s html=vi 
alias -s rb=vi 
#alias -s py=vi 
alias -s js=vi 
alias -s c=vi 
alias -s java=vi 
alias -s scala=vi 
alias -s txt=vi 
alias -s log=vi 
alias -s gz='tar -xzvf' 
alias -s tgz='tar -xzvf' 
alias -s zip='unzip' 
alias -s bz2='tar -xjvf'

export LC_ALL="zh_CN.UTF-8"

# virtualenv
#export WORKON_HOME=~/.virtualenv
#export PIP_REQUIRE_VIRTUALENV=true
#export VIRTUALENV_PYTHON=/usr/bin/python3
#source /usr/bin/virtualenvwrapper.sh
#workon fuyf

# ulimit
#ulimit -n 4096

#export PYTHONPATH=$PATHONPATH:.
#export CATALINA_HOME=/opt/tomcat
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.3.jdk/Contents/Home
export MVN_HOME=/usr/local/maven
export ANACONDA3_HOME=/anaconda
export KAFKA_HOME=/opt/kafka
export FLINK_HOME=/opt/flink
export HADOOP_HOME=/opt/hadoop-2.7.3
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export IGNITE_HOME=/opt/ignite
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$HOME/.cargo/bin:$MVN_HOME/bin:$FLINK_HOME/bin:$IGNITE_HOME/bin:$GOPATH/bin:$PATH

# 启用 Go Modules 功能
#export GO111MODULE=on
# 配置 GOPROXY 环境变量
export GOPROXY=https://goproxy.io,direct

alias ip="curl cip.cc"
alias proxy='export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087'
alias unproxy='unset http_proxy;unset https_proxy'

bindkey '^o' autosuggest-accept

# iterm2 advanced feature
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

alias goconda='source /Users/fuyifeng/miniconda3/bin/activate'

export SSLKEYLOGFILE="/Users/fuyifeng/ssl/key.log"

export HOMEBREW_BOTTLE_DOMAIN='https://mirrors.ustc.edu.cn/homebrew-bottles'
